Added tests
rsksmart/liquidity-bridge-contract pull request #44
Opened 2022-08-01 19:40 UTC by coolwather

2022-08-02 09:45 UTC, aguschirico approved these changes

2022-08-02 10:49 UTC, Vovchyk requested changes

2022-08-02 10:49 UTC, Vovchyk commented on test/basic.tests.js
> +        await truffleAssertions.fails(instance.register({from: currAddr, value : utils.LP_COLLATERAL}));
do you think we could use `truffleAssertions.reverts()` with an expected revert message in these tests?

2022-08-02 10:49 UTC, Vovchyk commented on test/basic.tests.js
> +    it('Should fail on register if not deposit the minimum collateral', async () => {
seems this test name is duplicated

2022-08-03 08:28 UTC, Vovchyk approved these changes

2022-08-03 08:29 UTC, merged